export type recipe = {
  id: number;
  title: string;
  text: string;
  kitchen_id: number;
  category_id: number;
  user_id: string;
  cookingTime: string;
  calories: number;
  rating: null | number;
  image: string;
  portion: number;
  weight: string;
  recipeImage: string;
  created_at: null | string;
  updated_at: null | string;
  kitchen: string;
  category: string;
  name: string;
};
